# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# Telegram Release Signing Configurations
RELEASE_STORE_PASSWORD=772997043aa
RELEASE_KEY_ALIAS=Telegram_anwer
RELEASE_KEY_PASSWORD=772997043aa
RELEASE_STORE_FILE=config/release.keystore
